Remove recursive self import from typings
With TypeScript 3.7, that line causes the following error, preventing TypeScript from compiling successfully:

```
node_modules/react-chartist/dist/index.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'ChartitGraphProps'.

1 import { ChartitGraphProps } from './index.d';
           ~~~~~~~~~~~~~~~~~

[7:11:32 PM] Found 1 error. Watching for file changes.
```

This resolves that error.